trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('pickup_list/', views.pickup_list, name="pickup_list"),
    path('pickup_confirm/<int:customer_id>', views.pickup_confirm, name="pickup_confirm"),
    path('sunday/',views.sunday, name="sunday"),
    path('monday/',views.monday, name="monday"),
    path('tuesday/',views.tuesday, name="tuesday"),
    path('wednesday/',views.wednesday, name="wednesday"),
    path('thursday/',views.thursday, name="thursday"),
    path('friday/',views.friday, name="friday"),
    path('saturday/',views.saturday, name="saturday"),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trash_collector/views.py for more info
    path('', views.group_redirect, name='home'),

]

trash_collector/employees/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.

# class Employee(models.Model):
#     name = models.CharField(max_length=50)
#     user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.name
class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=5)
    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from datetime import date
import calendar
from django.apps import apps
from django.contrib.auth import get_user_model


from .models import Employee


# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


@login_required
def index(request):
    # The following line will get the logged-in user (if there is one) within any view function
    logged_in_user = request.user
    try:
        # This line will return the employee record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=logged_in_user)

        today = date.today()
        
        context = {
            'logged_in_employee': logged_in_employee,
            'today': today
        }
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))

# def index(request):
#     # This line will get the employee model from the other app, it can now be used to query the db for employees
#     employee = apps.get_model('employees.employee')

#     return render(request, 'employees/index.html')

# Input employee information
@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
     
        new_employee = Employee(name=name_from_form, user=logged_in_user)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')


@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        address_from_form = request.POST.get('address')
        zip_from_form = request.POST.get('zip_code')
        weekly_pickup_from_form = request.POST.get('weekly')
        logged_in_employee.name = name_from_form
        logged_in_employee.address = address_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.weekly_pickup = weekly_pickup_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)


@login_required
def pickup_list(request):
    curr_date = date.today()
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    # customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(Q(weekly_pickup = (calendar.day_name[curr_date.weekday()])) | Q(one_time_pickup = (curr_date)))
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(Q(weekly_pickup = (calendar.day_name[curr_date.weekday()])) | Q(one_time_pickup = (curr_date))).exclude(Q(date_of_last_pickup = curr_date) | Q(suspend_end__gt= curr_date, suspend_start__lt=curr_date))
    context={
        "customer_zip" : customer_zip
    }      

    return render(request,'employees/pickup_list.html', context)

@login_required
def pickup_confirm(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer_object = Customer.objects.get(pk=customer_id)
    # date_pickup = customer_object.date_of_last_pickup
    customer_object.date_of_last_pickup = date.today()
    customer_object.balance -= 20
    customer_object.save()
  
        # Customer = apps.get_model('customers.Customer')
        # customer_pickup= Customer.objects.filter(zip_code = employee_zip)
        # context={
        #     "customer_zip" : customer_zip
        # }      
        # customer_balance +=20
        # customer_balance.save()
    # return render(request, 'employees/pickup_list.html',)
    return HttpResponseRedirect(reverse('employees:pickup_list'))
  
        # return render(request, 'employees/pickup_list.html', context)

@login_required
def sunday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Sunday")
    context={
        "customer_zip" : customer_zip
    }     
    return render(request,'employees/pickup_list.html', context)

@login_required
def monday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Monday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)


@login_required
def tuesday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Tuesday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)

@login_required
def wednesday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Wednesday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)

@login_required
def thursday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Thursday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)

@login_required
def friday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Friday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)

@login_required
def saturday(request):
    logged_in_user=request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    employee_zip= logged_in_employee.zip_code
    customer_zip= Customer.objects.filter(zip_code = employee_zip).filter(weekly_pickup="Saturday")
    curr_date = date.today()
    context={
        "customer_zip" : customer_zip,
        "curr_date": curr_date
    }      
    return render(request,'employees/pickup_list.html', context)

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Customer Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Address: <input type="text" name="address" id="address"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees\employee_base.html' %}

{% block title %} employee Profile Edit {% endblock %}

<!--{% block header %} Update Your Information {% endblock %}-->

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
<table  margin="auto">
    <col style = "width: 200px">
    <tr><td align="left">Name:</td> <td align="left"><input type="text" name="name" id="name" value="{{logged_in_employee.name}}"></td></tr>
    <br />
    <br />
    <tr><td align="left">Address:</td> <td align="left"> <input type="text" name="address" id="address" value="{{logged_in_employee.address}}"></td></tr>
    <br />
    <br />
    <tr><td align="left">Zip Code:</td> <td align="left"> <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}"></td></tr>
    <br />
    <br />
    <tr><td align="left">Weekly Pickup Day: </td> <td align="left"><input type="text" name="weekly" id="weekly" value="{{logged_in_employee.weekly_pickup}}"></td></tr>
</table>
    <br />
    <br />
    <input class = "btn-primary" type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}" style="color: black;">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}" style="color: black;">Edit Profile</a>
    <a class="nav-item nav-link" href="{% url 'employees:pickup_list' %}" style="color: black;">Pickup List</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Home {% endblock %}

{% block header %} Employee Portal {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
        Hello {{ logged_in_employee.name }}!<br />
        Address: {{ logged_in_employee.address }} {{logged_in_employee.zip_code }}<br />
  Current balance: $ {{ logged_in_employee.balance }}.00
        <br />
        <br />
        {% if today > logged_in_employee.suspend_start and today < logged_in_employee.suspend_end %}
          Your pickups are suspended until {{ logged_in_employee.suspend_end }}

        {% endif %}

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}"style="color: black;">Log In</a>
    <a href="{% url 'accounts:register' %}" style="color: black;">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/pickup_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pickup confirm</title>
</head>
<body>
    
</body>
</html>

trash_collector/employees/templates/employees/pickup_list.html
{% extends 'employees\employee_base.html' %}

{% block title %} Employee Pickup List {% endblock %}
{% block content %}
<br />
<form action="{% url 'employees:pickup_list' %}" method="post">
<h1>Pickup Routes</h1>
<head>
</head>
<p>
    {%csrf_token%}

<table class = "table table-hover">
  <thead>
    <tr>  
        <th>Name</th>
        <th>Weekly Pickup</th> 
        <th>Confirm Pickup </th>
        <th>One Time Pickup</th> 
        <th>Active</th> 
        <th>Date of last pickup</th>
    </tr>  
  </thead>
  <tbody>
    {% for customer in customer_zip%}     
    <tr><td>{{customer.name}} </td> 
        <td>{{customer.weekly_pickup}}</td> 
        <td><button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:pickup_confirm' customer.id %}" >Confirm</a></button></td>
        <td>{{customer.one_time_pickup}}</td>
        {% if customer.suspend_start <= curr_date and customer.suspend_end >= curr_date %}
        <td> NO </td>
        {% else %}
        <td> YES </td>
        {% endif %}
        <td>{{customer.date_of_last_pickup}}</td>
    </tr>
    {%endfor%}
  </tbody>
</table>
<h1>Select Day</h1>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:sunday' %}">Sunday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:monday' %}">Monday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:tuesday' %}">Tuesday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:wednesday' %}">Wednesday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:thursday' %}">Thursday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:friday' %}">Friday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "{% url 'employees:saturday' %}">Saturday</a></button>
<button type="button" class="btn-primary"><a class="btn-link" href = "https://www.youtube.com/watch?v=dQw4w9WgXcQ">Holiday</a></button>







</ul>
</p>
{% endblock %}